# Comment to a new issue.
issueOpened: >
  Thank your for raising a issue. We will try and get back to you as soon as possible.

  Be sure to :star: the repository for a priority response!

  Please make sure you have given us as much context as possible.

pullRequestOpened: >
  Thank your for submitting a pull request.

  Please make sure you have followed our contributing guidelines in CONTRIBUTING.md. We will review it as soon as possible.